# -*- coding: utf-8 -*-
"""Helloworld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNCSPtsRvtWi3nvNt7ugebnsYSg_90r4
"""

data = int(input("Enter your age"))
print(data)